language: node_js # Sets which engine use to build the project  
node_js: "node" # Specifies node version to use "node"="latest"
services: mongodb
cache:  
  directories:
    - "node_modules"
before_install:
- npm update
install:
- npm install
script:
- npm test
- npm run coveralls